name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - release/**
  pull_request:
    type:
      - opened
      - edited
      - reopened
      - synchronize
      - review_requested
    branches:
      - main
      - release/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: enter branch name
        required: false
        default: main

concurrency:
  group: ci-cd-${{ github.ref }}-1
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    name: Build and test the application
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build and test
        run: echo 'Application built and tested successfully'

  publish-container-image:
    name: Publish Container Image
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Build and publish container image
        run: echo 'Application container image published successfully'

  staging-deployment:
    name: Staging Deployment
    runs-on: ubuntu-latest
    environment: staging
    needs: [publish-container-image]

    steps:
      - name: Deploy to staging
        if: ${{ github.event_name != 'pull_request' }}
        run: echo 'Staging deployment completed'

  production-deployment:
    name: Production Deployment
    runs-on: ubuntu-latest
    environment: staging
    needs: [staging-deployment]

    steps:
      - name: Deploy to production
        if: ${{ github.event_name != 'pull_request' }}
        run: echo 'Production deployment completed'
