name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - release/**
  pull_request:
    type:
      - opened
      - edited
      - reopened
      - synchronize
      - review_requested
    branches:
      - main
      - release/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: enter branch name
        required: false
        default: main

concurrency:
  group: ci-cd-${{ github.ref }}-1
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build and test
        run: echo 'Application built and tested successfully'
    outputs:
      region: "ap-southeast-2"
      app_name: "unicorn-app"

  publish-container-image:
    name: Publish container image
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Build and publish container image
        run: echo 'Application container image published successfully ${{ needs.build-and-test.outputs.region }} ${{ needs.build-and-test.outputs.app_name }}'

  staging-deployment:
    name: Staging deployment
    runs-on: ubuntu-latest
    environment: staging
    needs: [publish-container-image]
    if: ${{ github.event_name != 'pull_request' }}

    steps:
      - name: Deploy to staging
        run: echo 'Staging deployment completed'
      - name: Tag
        run: |
          git tag stg-v1.${{github.run_number}}.${{github.run_attempt}}
          git push --tags

  production-deployment:
    name: Production deployment
    runs-on: ubuntu-latest
    environment: production
    needs: [staging-deployment]

    steps:
      - name: Deploy to production
        if: ${{ github.event_name != 'pull_request' }}
        run: echo 'Production deployment completed'
      - name: Tag
        run: |
          git tag prd-v1.${{github.run_number}}.${{github.run_attempt}}
          git push --tags
